#
# Module manifest for module 'ScriptClass'
#
# Generated by: adamed
#
# Generated on: 9/12/2017
#

@{

# Script module or binary module file associated with this manifest.
# Be VERY careful here -- 'scriptclass.psm1' vs '.\scriptclass.ps1' do
# different things -- the latter will cause publish-module to find
# a scriptclass.psm1 in a parent directory, and then it will publish
# the parent directory rather than something nested underneath as the
# output of a build! Do not precede with '.'!
# RootModule = ''

# Version number of this module.
ModuleVersion = '0.16.0'

# Supported PSEditions
CompatiblePSEditions = @('Desktop', 'Core')

# ID used to uniquely identify this module
GUID = '9b0f5599-0498-459c-9a47-125787b1af19'

# Author of this module
Author = 'Adam Edwards'

# Company or vendor of this module
CompanyName = 'Modulus Group'

# Copyright statement for this module
Copyright = '(c) 2019 Adam Edwards.'

# Description of the functionality provided by this module
Description = "Class definition extensions for PowerShell's object-based type system"

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
ScriptsToProcess = @('src/std.ps1')

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @('=>', '::>')

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    CmdletsToExport = @(
        'Add-ScriptClass',
        'Import-Assembly',
        'Import-Script',
        'Invoke-Method',
        'Mock-ScriptClassMethod',
        'New-ScriptObject',
        'New-ScriptObjectMock',
        'Test-ScriptObject',
        'Unmock-ScriptClassMethod')

# Variables to export from this module
VariablesToExport = @('::')

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @('new-so', 'scriptclass', 'with', 'const')

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
    FileList = @(
        './ScriptClass.psd1',
        './scriptclass.psm1',
        'src/Mock-ScriptClassMethod.ps1',
        'src/mock/MethodMocker.ps1',
        'src/mock/MethodPatcher.ps1',
        'src/mock/PatchedClassMethod.ps1',
        'src/mock/PatchedObject.ps1',
        'src/New-ScriptObjectMock.ps1',
        'src/scriptclass.ps1',
        'src/std.ps1',
        'src/Unmock-ScriptClassMethod.ps1',
        'src/include.ps1',
        'src/assemblyhelper.ps1')

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('class', 'object', 'PSCustomObject', 'netcore', 'PSEdition_Desktop', 'PSEdition_Core')

        # A URL to the license for this module.
        LicenseUri = 'http://www.apache.org/licenses/LICENSE-2.0'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/adamedx/scriptclass'

        # A URL to an icon representing this module.
        IconUri = 'https://raw.githubusercontent.com/adamedx/scriptclass/master/assets/ScriptClassIco.png'

        # ReleaseNotes of this module
        ReleaseNotes = @"
# ScriptClass 0.16.0 Release Notes

Compatibility fixes for Linux

## New features

* ``Import-Assembly`` syntax is more sane -- assembly name without '.dll' extension must be specified
* ``Import-Assembly`` now supports a platform precedence and will search for compatible platforms in a priority order among netstandard1.3, netstandard1.1, and netcoreapp1.0 monikers (in that order)
* ``Import-Assembly`` now returns a `System.Reflection.Assembly` if it loads an assembly successfully
* Added common parameters to Import-Assembly through cmdletbinding attribute

## Fixed defects

* Fix ``Import-Assembly`` so that it handles Linux paths with '/' characters
* Fix break in ``Import-Assembly`` by replacing use of ``ls`` alias with ``Get-ChildItem`` to avoid collision with Linux ``ls`` command
* Fix path case sensitivity issue with ``Import-Script`` where entire path of script file was lower-cased before attempting to load the file, which breaks on case-sensitive file systems like Linux
* Added missing test coverage for Import-Assembly

"@

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}
